/**
 * Diccionario ES/EN del landing. Fuente única de copy: el selector de idioma
 * cambia la variable de localización (persistida + ?lang= compartible) y
 * re-renderiza sin recargar. Sin mocks: todo texto visible sale de aquí.
 */

export type LandingLang = 'es' | 'en';

export const LANDING_LANG_KEY = 'inventa_lang';

const es = {
  nav_plataforma: 'Plataforma',
  nav_motor: 'Motor Predictivo IA',
  nav_motor_desc: 'Pronóstico a 30, 60 y 180 días',
  nav_jit: 'Reabastecimiento JIT',
  nav_jit_desc: 'Generación de OC en 1 clic',
  nav_erp: 'Conectores ERP & APIs',
  nav_erp_desc: 'SAP, Shopify, Amazon & SUNAT',
  nav_soluciones: 'Soluciones',
  nav_dist: 'Para Distribuidores & Mayoristas',
  nav_dist_desc: 'Eliminación de quiebres de stock',
  nav_fin: 'Financiamiento de Inventario',
  nav_fin_desc: 'Líneas de crédito rotativas B2B',
  nav_consorcios: 'Consorcios de Compra',
  nav_consorcios_desc: 'Descuentos por volumen agrupado',
  nav_precios: 'Precios',
  nav_recursos: 'Recursos',
  nav_guide: 'Guía de usuario',
  nav_learn: 'Aprender',
  nav_lang_label: 'Seleccionar idioma',
  acc_tagline: 'Inventario, pronóstico, reabastecimiento y finanzas',
  acc_cap1: 'Inventario',
  acc_cap2: 'Pronóstico',
  acc_cap3: 'Reabastecimiento',
  acc_cap4: 'Financiamiento',
  acc_cap5: 'Analítica',
  acc_eyebrow: 'Plataforma de operaciones',
  acc_title: 'Empiece ahora',
  acc_sub: 'Reserve una demo o entre con su cuenta. El acceso depende de su empresa y su rol.',
  acc_divider: 'O continúe con',
  acc_google: 'Google',
  acc_trial: 'Iniciar prueba gratis de 7 días',
  acc_lang_es: 'Español',
  acc_lang_en: 'English',
  acc_footer_left: 'INVENTA.AI Operaciones',
  acc_help: 'Ayuda',
  acc_support: 'Soporte',
  nav_login: 'Iniciar sesión',
  nav_demo: 'Reservar una demo',
  nav_trial: 'Iniciar prueba gratis de 7 días',
  nav_start: 'Empezar gratis',
  nav_dashboard: 'Ir al Dashboard',
  nav_menu: 'Menú principal',
  hero_eyebrow: 'PLATAFORMA',
  hero_title: 'El Cerebro de Compras para tu Empresa',
  hero_sub: 'Anticipa la demanda, evita quiebres de stock y financia inventario con inteligencia predictiva.',
  hero_cta_demo: 'Solicitar Demo',
  hero_cta_how: 'Ver cómo funciona',
  hero_light: 'o empieza gratis con el plan Light',
  hero_trust1: 'Plan Light gratuito',
  hero_trust2: 'Facturación Essential mensual o anual',
  hero_trust3: '14 días de gracia al bajar de plan',
  mockup_search: 'Buscar productos, stock, almacenes, órdenes...',
  mockup_live: 'INVENTA Core',
  mockup_crumb: 'INVENTA.AI › Overview',
  mockup_heading: 'Overview',
  mockup_sub: 'El algoritmo operó los últimos 30 días',
  mockup_insight:
    'El inventario está en buen estado general, con un puntaje de salud de 85. Muy por debajo de la tasa de quiebre de 1.2% (objetivo <3%). Demanda pronosticada a 30 días: 12,847 unidades en 4 almacenes.',
  mockup_kpi1: 'Stock Valorizado',
  mockup_kpi2: 'Pedidos Sincronizados',
  mockup_kpi3: 'Salud de Inventario',
  mockup_kpi4: 'Sedes Conectadas',
  mockup_chart: 'Demanda Real vs Pronóstico IA',
  mockup_real: 'Real',
  mockup_forecast: 'Forecast',
  mockup_avail: 'Disponibilidad',
  mockup_optimo: 'ÓPTIMO',
  mockup_enstock: 'En Stock',
  mockup_bajostock: 'Bajo Stock',
  mockup_filter: 'Filtrar',
  floating: '¿Encaja con mi negocio?',
  floating_aria: 'Consultar si encaja con mi negocio',
  trust_title: 'CONECTIVIDAD OFICIAL & COMPATIBILIDAD EMPRESARIAL VERIFICADA',
  sec_shopify: 'API Admin 2026',
  sec_meli: 'OAuth 2.0 Oficial',
  sec_amazon: 'SP-API v2',
  sec_sunat: 'Facturas & GRE',
  sec_soc: 'SOC 2 Type II Compliant',
  sec_aes: 'Cifrado AES-256 en Reposo',
  sec_uptime: '99.99% Uptime SLA',
  sec_cloud: 'Multi-Cloud AWS & GCP',
  prob_pre: 'EL COSTO OCULTO DEL MODELO TRADICIONAL',
  prob_title: 'El 34% del capital de trabajo de una empresa queda atrapado en inventario inmóvil',
  prob_sub:
    'Gestionar compras con intuición y tablas de Excel desactualizadas genera pérdidas silenciosas en quiebres de stock y sobrecostos financieros de almacenamiento.',
  prob_badge: 'El Riesgo Tradicional',
  prob_h: 'Compras Reactivas en Excel',
  prob_1t: 'Quiebres de stock imprevistos:',
  prob_1: 'Te enteras de que un producto clave se agotó cuando el cliente ya le compró a tu competidor.',
  prob_2t: 'Sobrestock y obsolescencia:',
  prob_2: 'Comprar lotes grandes para "aprovechar el precio" inmoviliza miles de soles en productos que no rotan.',
  prob_3t: 'Pérdida de poder de negociación:',
  prob_3: 'Comprar solo como empresa individual te obliga a aceptar los precios más altos del fabricante.',
  prob_4t: 'Desconexión con finanzas:',
  prob_4: 'El área de compras pide sin visibilidad de las líneas de crédito ni del flujo de caja proyectado.',
  sol_badge: 'Con INVENTA.AI',
  sol_h: 'Operación Autónoma & Predictiva',
  sol_1t: 'Forecast con 94.5% de exactitud:',
  sol_1: 'Algoritmos de Machine Learning anticipan la demanda a 30, 60 y 180 días considerando estacionalidad y tendencias.',
  sol_2t: 'Reabastecimiento Just-in-Time:',
  sol_2: 'Órdenes de compra generadas automáticamente en el momento exacto para no acumular inventario innecesario.',
  sol_3t: 'Poder de Compra Consolidada:',
  sol_3: 'Agrupación algorítmica de compras con otras empresas para acceder a descuentos por escala de hasta 18%.',
  sol_4t: 'Financiamiento de Inventario:',
  sol_4: 'Desbloqueo de líneas de crédito rotativas vinculadas directamente a la rotación de tus productos.',
  feat_pre: 'PILARES TECNOLÓGICOS',
  feat_title: 'Tres módulos diseñados para maximizar tu rentabilidad',
  feat_sub:
    'Una plataforma integral que une predicción de demanda, negociación de escala y liquidez inmediata para distribuidores y retailers.',
  feat1_t: 'Pronóstico Automático de Demanda',
  feat1_d:
    'Modelos de Deep Learning entrenados con tu histórico de ventas, estacionalidad, inflación y comportamiento de mercado. Genera predicciones precisas SKU por SKU a 30, 60 y 180 días.',
  feat1_a: 'Alertas de quiebre preventivas',
  feat1_b: 'Buffer de seguridad dinámico',
  feat1_c: 'Sugerencias de OC con 1 clic',
  feat2_t: 'Compras Conjuntas (Consorcios B2B)',
  feat2_d:
    'Unimos la demanda de múltiples distribuidores y PYMES para formar lotes de compra mayores. Accede a los precios y condiciones preferenciales que solo obtienen las corporaciones gigantes.',
  feat2_a: 'Hasta 18% ahorro en costo de producto',
  feat2_b: 'Negociación directa con fabricantes',
  feat2_c: 'Reducción de costos de flete',
  feat3_t: 'Financiamiento de Inventarios',
  feat3_d:
    'Líneas de crédito rotativas de capital de trabajo aprobadas en tiempo real en función de la rotación comprobada de tus SKUs y tus órdenes de compra en firme. Paga el inventario a medida que lo vendes.',
  feat3_a: 'Evaluación crediticia con datos de venta',
  feat3_b: 'Plazos de 30 a 90 días',
  feat3_c: 'Cero trámites bancarios tradicionales',
  roi_pre: 'IMPACTO MEDIBLE Y COMPROBADO',
  roi_title: 'Retorno de inversión garantizado desde el primer mes',
  roi_sub:
    'Métricas auditadas de empresas que reemplazaron hojas de cálculo por el motor de compras autónomo de INVENTA.AI.',
  roi1_t: 'Ahorro Promedio Generado (30d)',
  roi1_d:
    'Ahorro directo derivado de compras consolidadas, eliminación de fletes urgentes y optimización de capital inmovilizado.',
  roi2_t: 'Inventario Muerto',
  roi2_d:
    'Reducción de productos estancados en bodega gracias al rebalanceo preventivo y ajustes automáticos de lote económico.',
  roi3_t: 'Precisión de Forecast',
  roi3_d:
    'Exactitud comprobada frente a métodos basados en promedios móviles y hojas de cálculo (que promedian 61%).',
  case_tag: 'CASO DE ÉXITO VERIFICADO',
  case_company: 'Grupo Logístico Nacional S.A.C.',
  case_cat: 'Distribución de Consumo Masivo · 1,200 SKUs · 4 Almacenes',
  case_quote:
    '“Antes de INVENTA.AI perdíamos ventas todas las semanas por quiebres en nuestros 40 productos estrella, mientras teníamos S/ 300,000 atrapados en productos de baja rotación. En menos de 90 días redujimos los quiebres en 52% y liberamos S/ 120,000 en liquidez inmediata.”',
  case_stat1: 'Quiebres de Stock',
  case_stat2: 'Liquidez Liberada',
  case_stat3: 'Tiempo de Adopción',
  tech_pre: 'INFRAESTRUCTURA & SEGURIDAD ENTERPRISE',
  tech_title: 'Diseñado para escalar con los requerimientos técnicos más exigentes',
  tech_sub:
    'Arquitectura en la nube de alta disponibilidad, APIs abiertas y cumplimiento de estándares internacionales de protección de datos.',
  tech1_t: '99.99% Uptime SLA',
  tech1_d: 'Infraestructura redundante multi-región en AWS y Google Cloud con failover automático y balanceo de carga.',
  tech2_t: 'Seguridad de Grado Bancario',
  tech2_d: 'Cifrado AES-256 en reposo, TLS 1.3 en tránsito, autenticación OAuth 2.0 y compatibilidad con Single Sign-On (SSO).',
  tech3_t: 'APIs REST & Webhooks',
  tech3_d: 'Endpoints documentados con OpenAPI 3.0, webhooks firmados criptográficamente (HMAC-SHA256) y sincronización cada 5 min.',
  tech4_t: 'Cumplimiento Fiscal SUNAT',
  tech4_d: 'Integración directa con los Web Services de SUNAT y OSE para consulta de RUC, validación de CPEs y emisión de GRE.',
  cta_title: '¿Listo para transformar las compras de tu empresa?',
  cta_sub: 'Agenda una sesión estratégica de 15 minutos con nuestros especialistas de producto e ingeniería de datos.',
  cta_demo: 'Solicitar Demo 1:1',
  cta_explore: 'Explorar Dashboard',
  cta_micro: 'Sin tarjeta de crédito requerida · Onboarding asistido',
  foot_tagline: 'El cerebro de compras y financiamiento de inventario para empresas en América Latina.',
  foot_prod: 'Producto',
  foot_f1: 'Pronóstico de Demanda',
  foot_f2: 'Compras Conjuntas',
  foot_f3: 'Financiamiento de Stock',
  foot_f4: 'Integraciones ERP',
  foot_emp: 'Empresa',
  foot_e1: 'Prueba de ROI',
  foot_e2: 'Casos de Éxito',
  foot_e3: 'Seguridad & SLA',
  foot_e4: 'El Desafío',
  foot_sup: 'Soporte & Legal',
  foot_terms: 'Términos de Servicio',
  foot_priv: 'Política de Privacidad',
  foot_status: 'Estado del Sistema (Status)',
  foot_rights: '© 2026 INVENTA.AI Technologies Inc. Todos los derechos reservados.',
  foot_built: 'Desarrollado con estándares Enterprise B2B.',
  modal_pre: 'SESIÓN ESTRATÉGICA 1:1',
  modal_title: 'Solicitar Demo de INVENTA.AI',
  modal_sub: 'Descubre en 15 minutos cómo optimizar tu inventario y acceder a financiamiento rotativo.',
  modal_nombre: 'Nombre y Apellido *',
  modal_nombre_ph: 'Ej: Carlos Mendoza',
  modal_email: 'Correo Corporativo *',
  modal_empresa: 'Empresa *',
  modal_empresa_ph: 'Nombre de tu empresa',
  modal_tel: 'Teléfono / WhatsApp *',
  modal_vol: 'Volumen Mensual de Compras de Inventario',
  modal_submit: 'Confirmar y Agendar Demo 1:1',
  modal_priv: 'Respetamos tu privacidad. Tus datos están protegidos con cifrado y nunca serán compartidos con terceros.',
  modal_ok: '¡Solicitud Recibida con Éxito!',
  modal_ok_p1: 'Gracias',
  modal_ok_p2: 'Uno de nuestros Directores de Producto te contactará a',
  modal_ok_p3: 'y por WhatsApp a',
  modal_ok_p4: 'para coordinar tu demo personalizada.',
  modal_company: 'Empresa:',
  modal_range: 'Rango:',
  modal_dashboard: 'Ir al Dashboard mientras tanto',
  modal_close: 'Cerrar',
};

export type LandingCopy = typeof es;

const en: LandingCopy = {
  nav_plataforma: 'Platform',
  nav_motor: 'AI Predictive Engine',
  nav_motor_desc: 'Forecast at 30, 60 and 180 days',
  nav_jit: 'JIT Restocking',
  nav_jit_desc: '1-click PO generation',
  nav_erp: 'ERP Connectors & APIs',
  nav_erp_desc: 'SAP, Shopify, Amazon & SUNAT',
  nav_soluciones: 'Solutions',
  nav_dist: 'For Distributors & Wholesalers',
  nav_dist_desc: 'Stockout elimination',
  nav_fin: 'Inventory Financing',
  nav_fin_desc: 'Revolving B2B credit lines',
  nav_consorcios: 'Buying Groups',
  nav_consorcios_desc: 'Pooled volume discounts',
  nav_precios: 'Pricing',
  nav_recursos: 'Resources',
  nav_guide: 'User guide',
  nav_learn: 'Learn',
  nav_lang_label: 'Select language',
  acc_tagline: 'Inventory, forecasting, replenishment & finance',
  acc_cap1: 'Inventory',
  acc_cap2: 'Forecasting',
  acc_cap3: 'Replenishment',
  acc_cap4: 'Financing',
  acc_cap5: 'Analytics',
  acc_eyebrow: 'Operations platform',
  acc_title: 'Get started',
  acc_sub: 'Book a demo or sign in with your account. Access depends on your company and role.',
  acc_divider: 'Or continue with',
  acc_google: 'Google',
  acc_trial: 'Start a 7-day free trial',
  acc_lang_es: 'Español',
  acc_lang_en: 'English',
  acc_footer_left: 'INVENTA.AI Operations',
  acc_help: 'Help',
  acc_support: 'Support',
  nav_login: 'Log in',
  nav_demo: 'Book a demo',
  nav_trial: 'Start a 7-day free trial',
  nav_start: 'Get started free',
  nav_dashboard: 'Go to Dashboard',
  nav_menu: 'Main menu',
  hero_eyebrow: 'PLATFORM',
  hero_title: 'The Buying Brain for Your Business',
  hero_sub: 'Anticipate demand, prevent stockouts and finance inventory with predictive intelligence.',
  hero_cta_demo: 'Request Demo',
  hero_cta_how: 'See how it works',
  hero_light: 'or start free with the Light plan',
  hero_trust1: 'Free Light plan',
  hero_trust2: 'Essential monthly or annual billing',
  hero_trust3: '14-day grace period when downgrading',
  mockup_search: 'Search products, stock, warehouses, orders...',
  mockup_live: 'INVENTA Core',
  mockup_crumb: 'INVENTA.AI › Overview',
  mockup_heading: 'Overview',
  mockup_sub: 'The algorithm ran the last 30 days',
  mockup_insight:
    'Inventory is in good shape overall, with a health score of 85. Well below the 1.2% stock-out rate (target <3%). 30-day forecast demand is 12,847 units across 4 warehouses.',
  mockup_kpi1: 'Valued Stock',
  mockup_kpi2: 'Synced Orders',
  mockup_kpi3: 'Inventory Health',
  mockup_kpi4: 'Connected Sites',
  mockup_chart: 'Actual Demand vs AI Forecast',
  mockup_real: 'Actual',
  mockup_forecast: 'Forecast',
  mockup_avail: 'Availability',
  mockup_optimo: 'OPTIMAL',
  mockup_enstock: 'In Stock',
  mockup_bajostock: 'Low Stock',
  mockup_filter: 'Filter',
  floating: 'Is it a fit for my business?',
  floating_aria: 'Check if it fits my business',
  trust_title: 'OFFICIAL CONNECTIVITY & VERIFIED ENTERPRISE COMPATIBILITY',
  sec_shopify: 'Admin API 2026',
  sec_meli: 'Official OAuth 2.0',
  sec_amazon: 'SP-API v2',
  sec_sunat: 'Invoices & GRE',
  sec_soc: 'SOC 2 Type II Compliant',
  sec_aes: 'AES-256 Encryption at Rest',
  sec_uptime: '99.99% Uptime SLA',
  sec_cloud: 'Multi-Cloud AWS & GCP',
  prob_pre: 'THE HIDDEN COST OF THE TRADITIONAL MODEL',
  prob_title: '34% of a company’s working capital gets trapped in idle inventory',
  prob_sub:
    'Managing purchases by gut feeling and outdated Excel sheets creates silent losses from stockouts and financial overhead from storage.',
  prob_badge: 'The Traditional Risk',
  prob_h: 'Reactive Buying in Excel',
  prob_1t: 'Unexpected stockouts:',
  prob_1: 'You learn a key product ran out only after the customer already bought from your competitor.',
  prob_2t: 'Overstock and obsolescence:',
  prob_2: 'Buying big lots to "get the price" locks thousands in slow-moving products.',
  prob_3t: 'Lost bargaining power:',
  prob_3: 'Buying alone forces you to accept the manufacturer’s highest prices.',
  prob_4t: 'Disconnected from finance:',
  prob_4: 'Purchasing asks for budget with no visibility into credit lines or projected cash flow.',
  sol_badge: 'With INVENTA.AI',
  sol_h: 'Autonomous & Predictive Operation',
  sol_1t: '94.5% accurate forecast:',
  sol_1: 'Machine Learning algorithms anticipate demand at 30, 60 and 180 days, factoring seasonality and trends.',
  sol_2t: 'Just-in-Time restocking:',
  sol_2: 'Purchase orders generated automatically at the exact moment, avoiding excess inventory.',
  sol_3t: 'Consolidated Buying Power:',
  sol_3: 'Algorithmic pooling with other companies to unlock scale discounts of up to 18%.',
  sol_4t: 'Inventory Financing:',
  sol_4: 'Unlock revolving credit lines tied directly to your products’ turnover.',
  feat_pre: 'TECHNOLOGY PILLARS',
  feat_title: 'Three modules built to maximize your profitability',
  feat_sub:
    'One platform joining demand prediction, scale negotiation and instant liquidity for distributors and retailers.',
  feat1_t: 'Automatic Demand Forecasting',
  feat1_d:
    'Deep Learning models trained on your sales history, seasonality, inflation and market behavior. Accurate SKU-level predictions at 30, 60 and 180 days.',
  feat1_a: 'Preventive stockout alerts',
  feat1_b: 'Dynamic safety buffer',
  feat1_c: '1-click PO suggestions',
  feat2_t: 'Group Buying (B2B Consortia)',
  feat2_d:
    'We pool demand from multiple distributors and SMBs into larger buying lots. Get the preferential prices only giant corporations get.',
  feat2_a: 'Up to 18% savings on product cost',
  feat2_b: 'Direct negotiation with manufacturers',
  feat2_c: 'Lower freight costs',
  feat3_t: 'Inventory Financing',
  feat3_d:
    'Revolving working-capital credit lines approved in real time based on your SKUs’ proven turnover and firm purchase orders. Pay inventory as you sell it.',
  feat3_a: 'Credit scoring with sales data',
  feat3_b: '30 to 90 day terms',
  feat3_c: 'Zero traditional banking paperwork',
  roi_pre: 'MEASURED AND PROVEN IMPACT',
  roi_title: 'Guaranteed ROI from month one',
  roi_sub:
    'Audited metrics from companies that replaced spreadsheets with INVENTA.AI’s autonomous buying engine.',
  roi1_t: 'Average Savings Generated (30d)',
  roi1_d: 'Direct savings from consolidated buying, rush-freight elimination and idle-capital optimization.',
  roi2_t: 'Dead Inventory',
  roi2_d: 'Fewer stagnant warehouse products thanks to preventive rebalancing and automatic EOQ tweaks.',
  roi3_t: 'Forecast Accuracy',
  roi3_d: 'Proven accuracy vs moving-average and spreadsheet methods (averaging 61%).',
  case_tag: 'VERIFIED SUCCESS STORY',
  case_company: 'Grupo Logístico Nacional S.A.C.',
  case_cat: 'Mass Consumer Distribution · 1,200 SKUs · 4 Warehouses',
  case_quote:
    '“Before INVENTA.AI we lost sales every week to stockouts on our 40 star products, while holding S/ 300,000 in slow movers. In under 90 days we cut stockouts 52% and freed S/ 120,000 in immediate liquidity.”',
  case_stat1: 'Stockouts',
  case_stat2: 'Freed Liquidity',
  case_stat3: 'Adoption Time',
  tech_pre: 'ENTERPRISE INFRASTRUCTURE & SECURITY',
  tech_title: 'Built to scale with the most demanding technical requirements',
  tech_sub: 'High-availability cloud architecture, open APIs and compliance with international data-protection standards.',
  tech1_t: '99.99% Uptime SLA',
  tech1_d: 'Redundant multi-region infrastructure on AWS and Google Cloud with automatic failover and load balancing.',
  tech2_t: 'Bank-Grade Security',
  tech2_d: 'AES-256 at rest, TLS 1.3 in transit, OAuth 2.0 authentication and Single Sign-On (SSO) support.',
  tech3_t: 'REST APIs & Webhooks',
  tech3_d: 'OpenAPI 3.0 documented endpoints, cryptographically signed webhooks (HMAC-SHA256) and 5-min sync.',
  tech4_t: 'SUNAT Tax Compliance',
  tech4_d: 'Direct integration with SUNAT and OSE web services for RUC lookup, CPE validation and GRE issuance.',
  cta_title: 'Ready to transform your company’s buying?',
  cta_sub: 'Book a 15-minute strategy session with our product and data-engineering specialists.',
  cta_demo: 'Request 1:1 Demo',
  cta_explore: 'Explore Dashboard',
  cta_micro: 'No credit card required · Assisted onboarding',
  foot_tagline: 'The buying and inventory-financing brain for Latin American businesses.',
  foot_prod: 'Product',
  foot_f1: 'Demand Forecasting',
  foot_f2: 'Group Buying',
  foot_f3: 'Stock Financing',
  foot_f4: 'ERP Integrations',
  foot_emp: 'Company',
  foot_e1: 'ROI Proof',
  foot_e2: 'Success Stories',
  foot_e3: 'Security & SLA',
  foot_e4: 'The Challenge',
  foot_sup: 'Support & Legal',
  foot_terms: 'Terms of Service',
  foot_priv: 'Privacy Policy',
  foot_status: 'System Status',
  foot_rights: '© 2026 INVENTA.AI Technologies Inc. All rights reserved.',
  foot_built: 'Built to Enterprise B2B standards.',
  modal_pre: '1:1 STRATEGY SESSION',
  modal_title: 'Request an INVENTA.AI Demo',
  modal_sub: 'Discover in 15 minutes how to optimize inventory and unlock revolving financing.',
  modal_nombre: 'Full Name *',
  modal_nombre_ph: 'E.g.: Carlos Mendoza',
  modal_email: 'Work Email *',
  modal_empresa: 'Company *',
  modal_empresa_ph: 'Your company name',
  modal_tel: 'Phone / WhatsApp *',
  modal_vol: 'Monthly Inventory Buying Volume',
  modal_submit: 'Confirm and Book 1:1 Demo',
  modal_priv: 'We respect your privacy. Your data is encrypted and never shared with third parties.',
  modal_ok: 'Request Received Successfully!',
  modal_ok_p1: 'Thanks',
  modal_ok_p2: 'One of our Product Directors will contact you at',
  modal_ok_p3: 'and via WhatsApp at',
  modal_ok_p4: 'to schedule your personalized demo.',
  modal_company: 'Company:',
  modal_range: 'Range:',
  modal_dashboard: 'Go to Dashboard meanwhile',
  modal_close: 'Close',
};

export const LANDING_COPY: Record<LandingLang, LandingCopy> = { es, en };
