var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/ajustes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__03mnk9g._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ted_8b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xpcv9w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17y6r1f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_0lezfqa._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_ajustes_page_actions_00do2_d.js")
R.m(46711)
module.exports=R.m(46711).exports
