// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/dashboard/ajustes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ajustes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ajustes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/financiamiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/financiamiento">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/financiamiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/integraciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/integraciones">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/integraciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/inventario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inventario">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/inventario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/ordenes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ordenes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/ordenes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/predictiva/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/predictiva">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/predictiva/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/reabastecimiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reabastecimiento">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/reabastecimiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/cerebro/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/cerebro">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/cerebro/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/financiamiento/desembolso/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/financiamiento/desembolso">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/financiamiento/desembolso/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/financiamiento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/financiamiento">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/financiamiento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/ordenes/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ordenes/[id]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/ordenes/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/ordenes/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ordenes/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/ordenes/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/ordenes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/ordenes">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/ordenes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/reabastecimiento/oc/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/reabastecimiento/oc">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/reabastecimiento/oc/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/reabastecimiento/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/reabastecimiento">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/reabastecimiento/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/amazon/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/amazon/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/amazon/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/mercadolibre/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/mercadolibre/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/mercadolibre/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/mercadolibre/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/mercadolibre/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/mercadolibre/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/mercadolibre/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/mercadolibre/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/mercadolibre/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/sap/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/sap/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/sap/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/shopify/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/shopify/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/shopify/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/shopify/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/shopify/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/shopify/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/shopify/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/shopify/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/shopify/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/sunat/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/sunat/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/sunat/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/integraciones/whatsapp/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integraciones/whatsapp/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/integraciones/whatsapp/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
