var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/ordenes/page.js")
R.c("server/chunks/ssr/_0vvu-rk._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0z5ob0b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bf0c1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__07-cb6x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17y6r1f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_0lezfqa._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_ordenes_page_actions_0vo9461.js")
R.m(68538)
module.exports=R.m(68538).exports
